[package]
name = "advent"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
lazy_static = "1.4.0"
regex = "1.5"
